FROM base/archlinux
MAINTAINER Vincent Ambo <dev@tazj.in>

COPY $ARCH_PKG /tmp/tazblog-current.pkg.tar.xz

RUN pacman -U /tmp/tazblog-current.pkg.tar.xz --noconfirm

VOLUME /var/tazblog
EXPOSE 8000
CMD /usr/bin/tazblog
