# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "cloud.google.com/go";
    fetch = {
      type = "git";
      url = "https://code.googlesource.com/gocloud";
      rev = "76e973f7c1e722b4859698ace0daed4e7eccdc60";
      sha256 = "0m3ncaz0br67zmzsi76wwk6c00rqr8r7kiqgirnkcd1iwlql0qdr";
    };
  }
  {
    goPackagePath = "github.com/golang/protobuf";
    fetch = {
      type = "git";
      url = "https://github.com/golang/protobuf";
      rev = "4c88cc3f1a34ffade77b79abc53335d1e511f25b";
      sha256 = "0chbdc4q55z7myiwnbvhryc5ihf6cxh8p4w3c1imy2gyzjn9sf4r";
    };
  }
  {
    goPackagePath = "github.com/googleapis/gax-go";
    fetch = {
      type = "git";
      url = "https://github.com/googleapis/gax-go";
      rev = "bd5b16380fd03dc758d11cef74ba2e3bc8b0e8c2";
      sha256 = "1lxawwngv6miaqd25s3ba0didfzylbwisd2nz7r4gmbmin6jsjrx";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/golang-lru";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/golang-lru";
      rev = "7f827b33c0f158ec5dfbba01bb0b14a4541fd81d";
      sha256 = "1p2igd58xkm8yaj2c2wxiplkf2hj6kxwrg6ss7mx61s5rd71v5xb";
    };
  }
  {
    goPackagePath = "go.opencensus.io";
    fetch = {
      type = "git";
      url = "https://github.com/census-instrumentation/opencensus-go";
      rev = "b4a14686f0a98096416fe1b4cb848e384fb2b22b";
      sha256 = "1aidyp301v5ngwsnnc8v1s09vvbsnch1jc4vd615f7qv77r9s7dn";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "74dc4d7220e7acc4e100824340f3e66577424772";
      sha256 = "0563yswwqknxx2gsvl0qikn0lmwalilbng8i12iw4d3v40n23s0l";
    };
  }
  {
    goPackagePath = "golang.org/x/oauth2";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/oauth2";
      rev = "0f29369cfe4552d0e4bcddc57cc75f4d7e672a33";
      sha256 = "06jwpvx0x2gjn2y959drbcir5kd7vg87k0r1216abk6rrdzzrzi2";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "fde4db37ae7ad8191b03d30d27f258b5291ae4e3";
      sha256 = "16k4w4pzziq1kln18k5fg01qgk4hpzb5xsm7175kaky6d6gwyhg3";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "342b2e1fbaa52c93f31447ad2c6abc048c63e475";
      sha256 = "0flv9idw0jm5nm8lx25xqanbkqgfiym6619w575p7nrdh0riqwqh";
    };
  }
  {
    goPackagePath = "google.golang.org/api";
    fetch = {
      type = "git";
      url = "https://code.googlesource.com/google-api-go-client";
      rev = "573115b31dcba90b19c25508412495d63f86e804";
      sha256 = "0vs0783azc1ja5l2ijs9d2szysrs4gpg8blvpkjbslyr07ca0dha";
    };
  }
  {
    goPackagePath = "google.golang.org/genproto";
    fetch = {
      type = "git";
      url = "https://github.com/google/go-genproto";
      rev = "55e96fffbd486c27fc0d5b4468c497d0de3f2727";
      sha256 = "1nnz3rb3ppj9dvalyf7xz6cpndlvi4ra5wm5hlv34nn498zpqc70";
    };
  }
  {
    goPackagePath = "google.golang.org/grpc";
    fetch = {
      type = "git";
      url = "https://github.com/grpc/grpc-go";
      rev = "451cf373a706e089ca34abd9ea14cbc20b34c1fc";
      sha256 = "11sza0g00v8xlmm3sah51l93m2993g4lw89df76z9d9lyk094dl8";
    };
  }
]
