#!/bin/bash

readonly dhparam=$(openssl dhparam 2048 | base64 -w0)

echo "Inserting new DH parameter ..."
kubectl replace --force -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: nginx-dhparam
data:
  tls.dhparam: ${dhparam}
EOF

