#!/bin/bash
set -ueo pipefail

readonly server_conf=$(cat server.conf | base64 -w0)

echo "Replacing nginx configuration ..."
kubectl replace --force -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: nginx-config
data:
  server.conf: ${server_conf}
EOF
